language: java

env:
   secure: "BJrpXeOe5d5iiVLThFfigUJINq2eYDJMVf28ZFYHUiBmDSDHGuoaJUURL4UMOBDolMA4EhKYxqndMJ75I7SHxxzRcNSyZQbYE4JmEq/VvHD7z2ddIrZOrU+47CmwTifz9CHVzA6lkWAk7MQQfYfhhx+qjyoP+Y89MEn/NdETer0="

after_success:
  - mvn compile -Pmerge-reports -N
  - mvn coveralls:jacoco