language: java

env:
   secure: "OkFYNXvPgdRGL3juvdPyLWaDIwjxEgU7/aTxWC5DsSiTQVk8DyStZcfL8aquhlq6lcZpPReWgqQMyjHBK+hJ/FQ47+WqgbD5HLuFR5dWpaLWH7oSxjEtbER4JlhktMFJCGXyuCgnvdlEKAfBBjgm7jx9XhngkGv7yW3af23kU60="

after_success:
  - mvn compile -Pmerge-reports -N
  - mvn coveralls:jacoco